# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment variables
      run: echo "KAKAOMAP_API_KEY_JS=${{ secrets.KAKAOMAP_API_KEY_JS }}" >> .env
      env:
          KAKAOMAP_API_KEY_JS: ${{secrets.KAKAOMAP_API_KEY_JS}}
